




CREATE TABLESPACE ts_u_src
DATAFILE 'db_u_src.dat'
SIZE 100M
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE ts_3nf_cl
DATAFILE 'db_3nf_cl.dat'
SIZE 200M
 AUTOEXTEND ON NEXT 100M
 SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts_3nf_data
DATAFILE 'db_3nf_data_01.dat'
SIZE 200M
 AUTOEXTEND ON NEXT 100M
 SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts_star_cl
DATAFILE 'db_star_cl.dat'
SIZE 100M
 AUTOEXTEND ON
    NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts_star_data
DATAFILE 'db_star.dat'
SIZE 100M
 AUTOEXTEND ON NEXT 50M
 SEGMENT SPACE MANAGEMENT AUTO;
