 CREATE TABLE fct_sales
    (
      ID_SALE_STAR NUMBER GENERATED ALWAYS AS IDENTITY
      START WITH 1000 INCREMENT BY 1
    , ID_SRC        NUMBER NOT NULL
    , EMPLOYEE_ID   NUMBER NOT NULL
    , CLIENT_ID     NUMBER NOT NULL
    , POSITION_ID   NUMBER NOT NULL
    , RESTAURANT_ID NUMBER NOT NULL
    , GROUP_ID      NUMBER NOT NULL
    , TIME_ID       NUMBER NOT NULL
    , TIMESTMP      TIMESTAMP NOT NULL
    ) ;