 CREATE TABLE "U_3NF"."T_MENU"
    (
      "ID_SRC"        NUMBER NOT NULL ENABLE
    , "GROUP_NAME"    VARCHAR2 ( 10 BYTE ) NOT NULL ENABLE
    , "POSITION_NAME" VARCHAR2 ( 100 BYTE ) NOT NULL ENABLE
    , "PRICE"         NUMBER ( 8, 2 ) NOT NULL ENABLE
    , "IS_VALID"      VARCHAR2 ( 1 BYTE )
    )
    SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "TS_3NF_DATA" ;
