 CREATE TABLE dim_Rest
    (
      ID_REST NUMBER GENERATED ALWAYS AS IDENTITY
      START WITH 1000 INCREMENT BY 1
    , ID_SRC               NUMBER NOT NULL
    , NAME                 VARCHAR ( 100 ) NOT NULL
    , GROUP_NAME           VARCHAR ( 100 ) NOT NULL
    , ADDRESS              VARCHAR ( 100 ) NOT NULL
    , TELEPHONE            VARCHAR ( 100 ) NOT NULL
    , COUNTRY              VARCHAR ( 20 ) NOT NULL
    , CITY                 VARCHAR2 ( 100 ) NOT NULL
    , STATE_CODE           VARCHAR ( 100 ) NOT NULL
    , STATE_NAME           VARCHAR ( 100 ) NOT NULL
    , CENSUS_REGION        VARCHAR ( 2 ) NOT NULL
    , CENSUS_REGION_NAME   VARCHAR ( 30 ) NOT NULL
    , CENSUS_DIVISION      VARCHAR2 ( 2 ) NOT NULL
    , CENSUS_DIVISION_NAME VARCHAR2 ( 100 ) NOT NULL
    ) ; 