 CREATE TABLE dim_Group
    (
      ID_POSITION NUMBER GENERATED ALWAYS AS IDENTITY
      START WITH 1000 INCREMENT BY 1
    , ID_SRC     NUMBER NOT NULL
    , GROUP_NAME VARCHAR ( 50 ) NOT NULL
    , START_DATE DATE
    , END_DATE   DATE
    , IS_CURRENT VARCHAR2 ( 20 )
    ) ; 